// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG7YBFH79bdnuVoNqeUwQuaDJ5_ZNVUJc',
    appId: '1:363539620453:web:9fb6a422607ebec92b9c8c',
    messagingSenderId: '363539620453',
    projectId: 'temu-4793d',
    authDomain: 'temu-4793d.firebaseapp.com',
    storageBucket: 'temu-4793d.appspot.com',
    measurementId: 'G-460C200HXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvL7sGd_6OZ0PcwurxzJUc_a-uGFMUZfU',
    appId: '1:363539620453:android:ac3a2062485fea9c2b9c8c',
    messagingSenderId: '363539620453',
    projectId: 'temu-4793d',
    storageBucket: 'temu-4793d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlwuJ2ZXmiISsaYXWkog3IeX7QynGlxk',
    appId: '1:363539620453:ios:92bc0aa129e8e15e2b9c8c',
    messagingSenderId: '363539620453',
    projectId: 'temu-4793d',
    storageBucket: 'temu-4793d.appspot.com',
    iosBundleId: 'com.blaxmc.temuapp.temu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYlwuJ2ZXmiISsaYXWkog3IeX7QynGlxk',
    appId: '1:363539620453:ios:9c7638cf3bc2a4dd2b9c8c',
    messagingSenderId: '363539620453',
    projectId: 'temu-4793d',
    storageBucket: 'temu-4793d.appspot.com',
    iosBundleId: 'com.blaxmc.temuapp.temu.RunnerTests',
  );
}
